# -*- coding: utf-8 -*-
"""2318068_Febri_Maulana_Rokhman

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r3f-AyniFi_lT8jKVxh6En-EBUektw1p

# **1. Import Library**
"""

import cv2
import numpy as np
import pandas as pd
import os
from google.colab import drive

"""# **2. Mount Google Drive**"""

drive.mount('/content/drive')
folder_path = '/content/drive/MyDrive/ComputerVision/EkstraksiFitur/gambar'

"""# **3. Melakukan Konversi Citra BGR ke Grayscale**"""

import cv2

#Mendefinisikan variabel untuk menyimpan lokasi folder citra di dalam Google Drive
folder_path = '/content/drive/MyDrive/ComputerVision/EkstraksiFitur/gambar'

#Melakukan perulangan dengan kondisi akhir sesuai jumlah isi file di dalam folder
for file_name in os.listdir(folder_path):
    #Menentukan spesifikasi file citra yang akan digunakan, yaitu yang memiliki ekstensi.jpg, .jpeg, dan .png
    if file_name.endswith('.jpg') or file_name.endswith('.jpeg') or file_name.endswith('.png'):
        #Membaca file citra yang ada di dalam folder Google Drive
        image = cv2.imread(os.path.join(folder_path, file_name))
        #Melakukan konversi citra dari BGR menjadi Grayscale
        grayscale_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        #Menyimpan dan mendefinisikan nama file citra hasil konversi ke dalam folder Google Drive
        cv2.imwrite(os.path.join(folder_path, f"grayscale_{file_name}"), grayscale_image)
        #Mencetak pesan berhasil mengkonversi citra
        print(f'File {file_name} berhasil diubah menjadi grayscale.')

"""# **4. Melakukan Ekstraksi Fitur Tekstur pada 15 Citra**"""

import os
#Melakukan import library opencv yang digunakan untuk melakukan konversi color space
import cv2
#Melakukan import library NumPy yang digunakan untuk membentuk objek N-dimensional array
import numpy as np
#Melakukan import graycomatrix untuk menghitung matriks co-occurance tingkat keabuan, dan graycoprops untuk menghitung properti tekstur dari GLCM dari library skimage.feature
from skimage.feature import graycomatrix, graycoprops
#Melakukan import library Pandas yang digunakan untuk membaca isi file excel
import pandas as pd

#Mendefinisikan variabel untuk menyimpan lokasi folder citra di dalam Google Drive
folder_path = '/content/drive/MyDrive/ComputerVision/EkstraksiFitur/gambar'
#Membuat variabel array kosong yang akan digunakan untuk menampung nilai fitur hasil ekstraksi
nilai_fitur = []

#Melakukan perulangan dengan kondisi akhir sesuai jumlah isi file di dalam folder
for file_name in os.listdir(folder_path):
    #Menentukan spesifikasi file citra yang akan digunakan, yaitu yang memiliki ekstensi.jpg, .jpeg, dan .png
    if file_name.endswith(".jpg") or file_name.endswith('.jpeg') or file_name.endswith(".png"):
        #Membaca file citra yang ada di dalam folder Google Drive
        image = cv2.imread(os.path.join(folder_path, file_name))
        #Melakukan konversi citra dari BGR menjadi Grayscale
        grayscale_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        #Menghitung matriks co-occurance dari citra hasil konversi
        glcm = graycomatrix(grayscale_image, [1], [0, np.pi/4, np.pi/2, 3*np.pi/4], symmetric=True, normed=True)
        #Menghitung rata-rata properti tekstur energi dari GLCM
        energi = graycoprops(glcm, 'energy').mean()
        #Menghitung rata-rata properti tekstur kontras dari GLCM
        kontras = graycoprops(glcm, 'contrast').mean()
        #Menghitung rata-rata properti tekstur korelasi dari GLCM
        korelasi = graycoprops(glcm, 'correlation').mean()
        #Menghitung rata-rata properti tekstur homogenitas dari GLCM
        homogenitas = graycoprops(glcm, 'homogeneity').mean()
        #Menampung nilai fitur ke dalam variabel array nilai_fitur
        nilai_fitur.append([file_name, energi, kontras, korelasi, homogenitas])

        #Mencetak nama file
        print(f"File {file_name}:")
        #Mencetak nilai energi
        print(f"Energi: {energi:.3f}")
        #Mencetak nilai kontras
        print(f"Kontras: {kontras:.3f}")
        #Mencetak nilai korelasi
        print(f"Korelasi: {korelasi:.3f}")
        #Mencetak nilai homogenitas
        print(f"Homogenitas: {homogenitas:.3f}")
    else:
        #Mencetak nama file jika bukan gambar
        print(f"Nama File: {file_name}")

"""# **5. Simpan ke CSV**"""

output_path = '/content/drive/MyDrive/ComputerVision/EkstraksiFitur/fitur_tekstur_15citra.csv'
df = pd.DataFrame(nilai_fitur, columns=['File Name', 'Energy', 'Contrast', 'Correlation', 'Homogeneity'])
df.to_csv(output_path, index=False)

print(f"\nFile CSV berhasil disimpan di: {output_path}")

"""# **6. Simpan ke Excel**"""

# Simpan juga ke Excel
excel_path = '/content/drive/MyDrive/ComputerVision/EkstraksiFitur/fitur_tekstur_15citra.xlsx'
df.to_excel(excel_path, index=False)

print("File Excel juga berhasil disimpan!")